name: Build Document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check Out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Determine Version
        id: version
        uses: paulhatch/semantic-version@9f72830310d5ed81233b641ee59253644cd8a8fc
        with:
          # Since version 6.0.0, the action uses conventional commits.
          major_pattern: "/(major)/i"
          minor_pattern: "/(minor)/i"

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@6549dc21effb2730855a1281407ecfcececc6c1b
        with:
          root_file: Diplom.tex

      - name: Create Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          files: out/Diplom.pdf
          generate_release_notes: true

